-- 1.1.0 在本地分析与固定分支间加入只读复核；风险意见不一致时不给予自动写入资格。
insert into workflow.version(workflow_id, tenant_id, workspace_id, asset_version, input_schema, output_schema,
                             entry_step_id, steps_json, status)
values ('58000000-0000-4000-8000-000000000001', '70000000-0000-4000-8000-000000000001',
        '10000000-0000-4000-8000-000000000001', '1.1.0',
        '{"type":"object","required":["customerId"],"additionalProperties":false,"properties":{"customerId":{"type":"string","minLength":1,"maxLength":160}}}',
        '{"type":"object","required":["riskLevel","reviewRiskLevel","summary","followupCreated","reviewConflict"],"additionalProperties":false,"properties":{"riskLevel":{"type":"string","enum":["LOW","MEDIUM","HIGH","UNKNOWN"]},"reviewRiskLevel":{"type":"string","enum":["LOW","MEDIUM","HIGH","UNKNOWN"]},"summary":{"type":"string"},"followupCreated":{"type":"boolean"},"reviewConflict":{"type":"boolean"}}}',
        'analyze',
        '[
          {"id":"analyze","type":"RUN_CAPABILITY","nextStepId":"peer-review","capabilityId":"54000000-0000-4000-8000-000000000001","capabilityVersion":"1.0.0","toolName":null,"toolVersion":null,"inputMapping":{"input":"$.input.customerId"},"conditionPath":null,"conditionValue":null,"whenTrueStepId":null,"whenFalseStepId":null,"outputMapping":{}},
          {"id":"peer-review","type":"RUN_TOOL","nextStepId":"peer-high","capabilityId":"54000000-0000-4000-8000-000000000001","capabilityVersion":"1.1.0","toolName":"agent.risk.review","toolVersion":"1.0.0","inputMapping":{"customerId":"$.input.customerId","riskSummary":"$.steps.analyze.output.summary"},"conditionPath":null,"conditionValue":null,"whenTrueStepId":null,"whenFalseStepId":null,"outputMapping":{}},
          {"id":"peer-high","type":"BRANCH","nextStepId":null,"capabilityId":null,"capabilityVersion":null,"toolName":null,"toolVersion":null,"inputMapping":{},"conditionPath":"$.steps.peer-review.output.riskLevel","conditionValue":"HIGH","whenTrueStepId":"local-high-peer-high","whenFalseStepId":"local-high-peer-not-high","outputMapping":{}},
          {"id":"local-high-peer-high","type":"BRANCH","nextStepId":null,"capabilityId":null,"capabilityVersion":null,"toolName":null,"toolVersion":null,"inputMapping":{},"conditionPath":"$.steps.analyze.output.riskLevel","conditionValue":"HIGH","whenTrueStepId":"create-followup","whenFalseStepId":"complete-conflict","outputMapping":{}},
          {"id":"local-high-peer-not-high","type":"BRANCH","nextStepId":null,"capabilityId":null,"capabilityVersion":null,"toolName":null,"toolVersion":null,"inputMapping":{},"conditionPath":"$.steps.analyze.output.riskLevel","conditionValue":"HIGH","whenTrueStepId":"complete-conflict","whenFalseStepId":"complete-no-action","outputMapping":{}},
          {"id":"create-followup","type":"RUN_TOOL","nextStepId":"complete-created","capabilityId":"54000000-0000-4000-8000-000000000001","capabilityVersion":"1.0.0","toolName":"crm.followup.create","toolVersion":"1.0.0","inputMapping":{"customerId":"$.input.customerId","summary":"$.steps.analyze.output.summary"},"conditionPath":null,"conditionValue":null,"whenTrueStepId":null,"whenFalseStepId":null,"outputMapping":{}},
          {"id":"complete-conflict","type":"COMPLETE","nextStepId":null,"capabilityId":null,"capabilityVersion":null,"toolName":null,"toolVersion":null,"inputMapping":{},"conditionPath":null,"conditionValue":null,"whenTrueStepId":null,"whenFalseStepId":null,"outputMapping":{"riskLevel":"$.steps.analyze.output.riskLevel","reviewRiskLevel":"$.steps.peer-review.output.riskLevel","summary":"$.steps.analyze.output.summary","followupCreated":"literal:false","reviewConflict":"literal:true"}},
          {"id":"complete-no-action","type":"COMPLETE","nextStepId":null,"capabilityId":null,"capabilityVersion":null,"toolName":null,"toolVersion":null,"inputMapping":{},"conditionPath":null,"conditionValue":null,"whenTrueStepId":null,"whenFalseStepId":null,"outputMapping":{"riskLevel":"$.steps.analyze.output.riskLevel","reviewRiskLevel":"$.steps.peer-review.output.riskLevel","summary":"$.steps.analyze.output.summary","followupCreated":"literal:false","reviewConflict":"literal:false"}},
          {"id":"complete-created","type":"COMPLETE","nextStepId":null,"capabilityId":null,"capabilityVersion":null,"toolName":null,"toolVersion":null,"inputMapping":{},"conditionPath":null,"conditionValue":null,"whenTrueStepId":null,"whenFalseStepId":null,"outputMapping":{"riskLevel":"$.steps.analyze.output.riskLevel","reviewRiskLevel":"$.steps.peer-review.output.riskLevel","summary":"$.steps.analyze.output.summary","followupCreated":"literal:true","reviewConflict":"literal:false"}}
        ]'::jsonb,
        'DRAFT');
